### ISSUE TITLE
Python-scripting week2

### ISSUE THREAD

**Issue by Sgarey-matc** [madisoncollege-it-programs/python-scripting-Sgarey-matc#1]
Had a little bit of trouble trying to create the file and getting everything in the spot and order but other then that it was good, learned a lot.

**Comment by cethenmc** [comment]
Seiji, the first looks good.  After class you said you thought you got assignment2 for week2, but I don't see it checked in yet.  Are you sure you don't want a hand?  You need to create a new issue when you have pushed that to github to be graded.  Thanks. ~Chris

**Comment by cethenmc** [comment]
Please create a new issue when assignment 2 is out there.

**Comment by cethenmc** [comment]
Reopening this for week #2, assignment #2, which we still need to see made executable at the command line.

1. add the shebang at the top of the file.
2. chmod u+x first-script.py
3. git add .
4. git commit -m "Made executable at the command line level"
5. git push

Thanks.

Chris

**Comment by cethenmc** [comment]
Thanks for hanging out after class to ensure we have this!
