### ISSUE TITLE
midterm ready for grading

### ISSUE THREAD

**Issue by Sgarey-matc** [madisoncollege-it-programs/python-scripting-Sgarey-matc#6]

**Comment by cethenmc** [comment]
• Midterm-if:  I like the creativity of using a concept we did not learn in this class yet.  I assume you could not recall a method to extract the line number as requested.  As a result of not extracting the line number and converting it to an int (which was a hint to help you know what you might use to extract), you will receive a score of 29/33.
	• Midterm-jpark:  Thanks for putting in a very solid effort on this part of the midterm.  The first part I analyze is program execution.  When I enter false username and password combos three times, the third failure should only render the magic word clause 25 times.  You keep the single occurrence with the counter firing on that last one (1 pt).  Unfortunately, dnedry/please does not work at all for logging in.  I looked in your code to find that you used a capital P (sort of like Sgarey in GitHub:-)).  So, I let you off the hook on that, but then I quickly realized, I could log in using nothing in user name and nothing in password, or d in username and nothing in password, or e in username and a in password.  Lines 18 and 19 in the code get you in much trouble from a security standpoint; do you see why?  (2 pts)  Lines 30 - 35 should fall into one if statement without hardcoding.  The evaluation can be done given the input and against the dictionary in a couple of lines (2 pts).  Score 28/33.
	• Midterm-slicing: Way to bring it home!  I could be picky, as you could have not done the join and then back to splitting again, but it definitely did the trick!  34/34
